# .github/workflows/extract-zip.yml
name: Extrair e inspecionar ZIP

on:
  push:
    paths:
      - 'nevermiss-2-em-1.zip'
  workflow_dispatch:

jobs:
  extract_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Mostrar arquivos do repositório
        run: |
          echo "Diretório de trabalho: $(pwd)"
          ls -la .

      - name: Verificar existência do ZIP
        run: |
          if [[ -f "nevermiss-2-em-1.zip" ]]; then
            echo "ZIP encontrado!"
          else
            echo "❌ nevermiss-2-em-1.zip NÃO encontrado!"
            exit 1
          fi

      - name: Descompactar ZIP
        run: |
          mkdir -p extracted
          unzip -o nevermiss-2-em-1.zip -d extracted

      - name: Listar conteúdo extraído
        run: ls -R extracted/

      - name: Fazer upload do conteúdo extraído
        uses: actions/upload-artifact@v3
        with:
          name: arquivos-extraidos
          path: extracted/
